Техническое задание 14
ChernakovaMSPB/java-shareit pull request #2
Opened 2023-06-21 15:20 UTC by ChernakovaMSPB

Техническое задание 14

2023-06-22 14:04 UTC, zgreen3 requested changes
Привет. 
Проверил проект, в целом он соответствует ТЗ, отлично.
Комментариев не много, потому что основные пункты ТЗ соблюдены и использование пройденных в спринте механизмов Spring и Spring Boot технически корректно. 
После принятия к сведению комментариев (+/-внесения правок по комментарию "Надо исправить"), присылай работу на завершение проверки.
Спасибо.

2023-06-22 14:04 UTC, zgreen3 commented on src/main/resources/schema.sql
> +    ADD CONSTRAINT requests_users_fk FOREIGN KEY (users_id)
Отлично:

Вижу, что здесь корректно написаны DDL SQL-выражения для создания таблиц для основных сущностей проекта (причём, даже не только для Item и User, как требовалось по ТЗ), отлично!

Для информации:

Полезно иметь ввиду, что в синтаксисе PostgreSQL допустимы разные варианты указания внешнего ключа: https://stackoverflow.com/a/28560619 , на разных рабочих проектах могут встретиться все 4, какое-либо предпочтение между ними сложно определить, поэтому выбор синтаксиса обычно зависит от договорённостей внутри команды проекта (общего для команды стиля написания sql-кода).

2023-06-22 14:04 UTC, zgreen3 commented on src/main/java/ru/practicum/shareit/item/Item.java
> +    @Column(name = "is_available")
Отлично:

Вижу, что ты в целом разобралась в написании основных классов сущностей (моделей) для репозиториев данного проекта с использованием аннотаций JPA, отлично!

2023-06-22 14:04 UTC, zgreen3 commented on src/main/resources/application.properties
> +#spring.datasource.driver-class-name=org.postgresql.Driver
Можно лучше:

Раз в этом файле уже используются (в коде далее, с 17 строки) отдельные профили для непрерывной интеграции и тестов (spring.config.activate.on-profile=ci,test), то не имеет смысла и даже было бы ошибочно в реальном, не учебном, проекте комментировать параметры для работы с БД PostgreSQL в итоговой сборке проекта для production-а / промышленной эксплуатации (run configuration в IDE, кстати, всегда можно настроить на запуск приложения с определённым флагом для профиля, чтобы, например, отдельно запускать его для "обычной" работы, а отдельно с профилем / в конфигурации для тестов и т.д., без необходимости комментировать участки с ненужными параметрами перед запуском, в т.ч. чтобы потом случайно в ветку общего репозитория команды не запушить закоментированные важные параметры, которые потом могут уйти в prod-акшн).

Т.е. целесообразно раскомментировать эти параметры для основной БД.

2023-06-22 14:04 UTC, zgreen3 commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
>  public class UserServiceImpl implements UserService {
Отлично:

Вижу, что в целом корректно (в соответствии со схемой БД и с описаниями в ТЗ) доработаны репозитории, а также сервисы для Item и User, отлично!

2023-06-22 14:04 UTC, zgreen3 commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    public ItemDto getItemById(Long itemId, Long requestorId) {
Надо исправить:

Здесь происходит выборка всех-всех вещей из репозитория лишь для того, чтобы отобрать только вещи, принадлежащие одному пользователю, если вещей будет много миллионов (как на крупных площадках), а запросов будет также много в минуту, это может заставить сервис "зависнуть". 

Нужно попробовать написать JPQL-запрос ИЛИ ещё проще - запросный метод с JOIN-ом таблиц items и users и фильтрацией по userId в поле owner на уровне репозитория вещей и использовать его здесь.

Аналогичный комментарий справедлив и для других методов поиска в слое сервисов. 
При этом мне достаточно, что ты продемонстрируешь только на примере правки данного метода понимание того, как избегать поиска через findAll() и проводить сужение (фильтрации) поиска до необходимого минимума данных из БД.
Т.к. переделывать аналогичным образом другие методы может быть весьма трудозатратно и избыточно с т.з. обучения=).

2023-06-24 14:00 UTC, ChernakovaMSPB commented on src/main/resources/application.properties
> +#spring.datasource.driver-class-name=org.postgresql.Driver
Изначально загружала проект и не коммитила параметры для БД PostgreSQL, но почему-то тесты на гите не проходили из-за этого, а удалять совсем не стала.

2023-06-24 14:01 UTC, ChernakovaMSPB commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    public ItemDto getItemById(Long itemId, Long requestorId) {
Подправила код

2023-06-24 19:41 UTC, zgreen3 commented on src/main/resources/application.properties
> +#spring.datasource.driver-class-name=org.postgresql.Driver
Понял, тогда да, лучше оставить закомментированные настройки, согласен, потому что углубляться в разбор причин этого думаю, что нецелесообразно для данного учебного проекта (я пунктирно посмотрел, что за автотесты вызываются, пока не обнаружил препятствий для наличия настроек PostgreSQL в них).

2023-06-24 19:43 UTC, zgreen3 approved these changes
Привет, вижу, что нужный комментарий учтён, отлично! 
Принимаю проект в текущем виде, встретимся на проверке следующих проектов.

2023-06-26 10:03 UTC, merged