Техническое задание 16
ChernakovaMSPB/java-shareit pull request #4
Opened 2023-07-07 19:02 UTC by ChernakovaMSPB

2023-07-09 21:22 UTC, zgreen3 requested changes
Привет. 
Проверил проект, он соответствует ТЗ, отлично (он хорошо проработан и у меня нет каких-либо существенных комментариев, требующих правок кода по нему)!
После принятия к сведению комментариев в коде присылай работу на завершение проверки.
Спасибо.

2023-07-09 21:22 UTC, zgreen3 commented on docker-compose.yml
> +#    image: postgres:14.8
Для информации:

Если нужна 14-ая версия Postgresql, то можно попробовать образ `postgres:14-alpine`.

2023-07-09 21:22 UTC, zgreen3 commented on docker-compose.yml
> +version: '3.8'
Отлично:

Вижу, что ты разобралась в теме объединения ряда докер образов в единой docker-compose конфигурации. 
Это точно пригодится тебе не раз в будущих рабочих проектах (на базе микросервисной и т.н. SOA-архитектуры).

1. Также небольшой доп. комментарий, для информации, про текущую (по состоянию на 2023 г.)) ситуацию с docker-compose API:
Поддержка Compose версии 1 (Docker Compose V1) больше не предоставляетсяся (начиная с июня 2023 года) и будет удалена из всех будущих версий Docker для всех основных ОС (Windows, Mac, Unix-like),
источник - https://www.docker.com/blog/new-docker-compose-v2-and-v1-deprecation/
Там ничего радикально не изменится с т.з. пользователей docker-compose (т.е. с т.з. разработчиков в основном это многочисленные улучшения процесса сборки compose-системы из докер-образов). 
Самое существенное для пользователей - теперь вызов compose будет осуществляться в командной строке так "docker compose" а не как раньше, "docker-compose" =), источник - https://docs.docker.com/compose/migrate/#:~:text=Compose%20V1%20no%20longer%20receives,Docker%20Desktop%20after%20June%202023.

2. Также для информации - некоторые детали о том, чем отличаются команды в файле docker-compose
(если тебе уже это известно, отлично, пишу для того, чтобы важные нюансы синтаксиса docker-compose.yml файла были собраны в 1 месте): 

- команда build, например, "build: gateway" - в данном случае это относительный путь, начиная от директории, где находится сам файл docker-compose.yml, для поиска Dockerfile, 
т.е. это аналог использования "./gateway/Dockerfile" при сборке докер-компоузом контейнера для gateway из такого докер-файла.

- команда image, например, "image: shareit-gateway" - это название докер-образа в локальном репозитории на твоей ОС (docker registry), 
в котором движок докер-компоуз будет искать докер-образ с этим названием (кстати, проверить имеющиеся на данный момент в локальном репозитории докер-образы, 
собранные из локальных Dockerfile-ов или скачанные из интернета, например, из Docker Hub, можно такой командой "docker compose images"),
см. детали тут https://docs.docker.com/compose/compose-file/build/ и тут https://docs.docker.com/compose/compose-file/05-services/

- команда container_name, например, "container_name: shareit-gateway" - это просто название контейнера, которое будет использоваться докер-компоуз для локальной идентификации контейнера 
(оно же отображается по команде "docker container ls", см. https://stackoverflow.com/questions/55522620/docker-compose-yml-container-name-and-hostname).

2023-07-09 21:22 UTC, zgreen3 commented on docker-compose.yml
> +      - SHAREIT_SERVER_URL=http://shareit-server:9090
Можно иначе:

Насколько могу судить из документации о сетевом взаимодействии контейнеров внутри docker compose конфигурации (см. детали тут, https://docs.docker.com/compose/networking/), название сервиса, который будет на уровне сети docker compose расшифрован в внутренний IP адрес, должно совпадать с названием контейнера в docker-compose.yml файле, т.е., вероятно, такой вариант указания url, `SHAREIT_SERVER_URL=http://server:9090`, корректнее такого `SHAREIT_SERVER_URL=http://shareit server:9090`.

2023-07-09 21:22 UTC, zgreen3 commented on gateway/src/main/resources/application.properties
> +shareit-server.url=${SHAREIT_SERVER_URL}
Для информации:

Такой вариант задания url здесь также вполне допустим и корректен: shareit-server.url=http://localhost:9090
 
При этом важно иметь ввиду, что при запуске docker-compose конфигурации (в Spring Boot приложениях), это свойство (url) всегда перезаписывается тем, которое указано в docker-compose.yml файле, 
`SHAREIT_SERVER_URL=http://server:9090` 

(по правилам конвертации переменной окружения в свойство проекта Spring Boot из docker-compose.yml файла - шире из окружения, environment, уровня ОС, см. описание этого здесь, 
https://stackoverflow.com/questions/73584692/spring-boot-application-properties-variable-conversion-matching-when-retrieved-f , в частности, о приоритете переменных окружения над свойствами из файла application.properties, здесь, https://docs.spring.io/spring-boot/docs/2.7.x/reference/html/features.html#features.external-config , и о правилах трансформации этих переменных в эти свойства в Spring Boot, здесь, https://docs.spring.io/spring-boot/docs/2.7.x/reference/html/features.html#features.external-config.typesafe-configuration-properties.relaxed-binding.environment-variables).
Поэтому явно указывать здесь, что shareit-server.url=${SHAREIT_SERVER_URL} , избыточно.

Также (для лучшего ориентирования в причинах указания тех или иных настроек в разных местах проекта) важно понимать, почему в файле docker-compose.yml может быть указан другой url адрес (например, http://server:9090), отличный от возможного к указанию в application.properties (http://localhost:9090): 

дело в том, что все докер-контейнеры, запущенные в одном docker-compose файле, работают по умолчанию в одной виртуальной сети, где их серверы имеют доменные имена по именам самих сервисов, указанных в этом файле, см., например, упоминание об этом тут, https://stackoverflow.com/a/66171015.

2023-07-09 21:22 UTC, zgreen3 commented on server/src/main/resources/application.properties
>  #---
Для информации, +/-Можно лучше:

Такие разделители-комментарии, `#--`, не случайны в этом файле, они задают множество вариантов настроек в едином документе (см., например, детали, тут, https://docs.spring.io/spring-boot/docs/3.0.0-M4/reference/htmlsingle/#features.external-config.files.multi-document).

Раз в этом файле уже используются (в коде далее, с 17 строки) отдельные профили для непрерывной интеграции и тестов (spring.config.activate.on-profile=ci,test), то имеет смысл попробовать раскомментировать настройки для "промышленной" конфигурации и использовать, совместно с профилем далее, БД с "промышленной" конфигурацией PostgreSQL. 
Главное, чтобы над "промышленной" конфигурацией, которая будет активирована по умолчанию также присутствовали такие разделители-комментарии `#--`. Т.о. вид файла server resources/application.properties может быть таким (привожу его для примера, не сопоставляя в деталях с имеющимся у тебя вариантом):
```
server.port=9090

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL10Dialect
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always

#---
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5434/shareit
spring.datasource.username=shareit
spring.datasource.password=shareit
#---
spring.config.activate.on-profile=ci,test
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:shareit
spring.datasource.username=test
spring.datasource.password=test
```

2023-07-09 21:22 UTC, zgreen3 commented on server/Dockerfile
> +FROM amazoncorretto:11
Отлично:

Отлично, вижу, что ты разобралась в создании базовых докер-файлов, на основе которых можно запускать (независимо от docker-compose.yml файла) докер-образ из контейнера, описанного здесь!
В рабочих проектах это бывает полезно как для отладки какого-либо отдельного сервиса в микросервисной архитектуре, так и для создания целых интергационных тестов (например, на основе фреймворка Testcontainers, https://www.testcontainers.org/ , прямо в коде Java, в тестовых классах)!

2023-07-09 21:22 UTC, zgreen3 commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +@Validated
Отлично:

Вижу, что валидация на уровне всех контроллеров, с которыми непосредственно работают пользователи, корректно вынесена в данный сервис gateway (и остальные подобные), в т.ч. добавлены недостающие в проекте-образце из ТЗ методы-эндпоинты в контроллер BookingController (а также добавлена требующаяся при этом обработка исключений) - всё в полном соответствии с ТЗ!

2023-07-09 21:22 UTC, zgreen3 commented on pom.xml
> +        <module>gateway</module>
Отлично:

Вижу, что у тебя корректно (здесь и в корневом pom-файле, в разделе `<modules> ... </modules>`) настроен мультимодульный Spring Boot Maven-проект, отлично!

2023-07-10 07:17 UTC, ChernakovaMSPB commented on docker-compose.yml
> +#    image: postgres:14.8
Благодарю за информацию, убрала лишнюю строку.

2023-07-10 07:17 UTC, ChernakovaMSPB commented on docker-compose.yml
> +      - SHAREIT_SERVER_URL=http://shareit-server:9090
Исправила

2023-07-10 07:18 UTC, ChernakovaMSPB commented on gateway/src/main/resources/application.properties
> +shareit-server.url=${SHAREIT_SERVER_URL}
Исправила

2023-07-10 07:19 UTC, ChernakovaMSPB commented on server/src/main/resources/application.properties
>  #---
Исправила

2023-07-10 07:50 UTC, zgreen3 approved these changes
Вижу, что ты учла все важные комментарии, отлично! 
Принимаю проект в текущем виде. 
Успехов в освоении заключительных тем курса и в реализации дипломного проекта!

2023-07-10 08:30 UTC, merged